### ISSUE TITLE
[info] installation packages

### ISSUE THREAD

**Issue by ewok** [jeffgreenca/todoist-add#3]
Hi!
I like the simplicity of your tool. thx!

I use arch based Linux, so I made an installation package in AUR.
https://aur.archlinux.org/packages/todoist-add-git/

**Comment by jeffgreenca** [comment]
Very cool

**Comment by jeffgreenca** [comment]
If you like, submit a PR to update the Installation section with instructions for arch

**Comment by jeffgreenca** [comment]
Thanks for your contribution
